# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 063caf2c4ea2bac1f166e36ec4842e9cdf1907291c0de3bb3c64ee62aef8cb8d5a23a36eb5e046bb031765129f345b1a70cd40199c2acb51a2b319dbadc6b765

test:
  secret_key_base: 562be13778f06229a8eb91af1dc97a7ef8e408cd4cdc0688e4b3e040259b6726c7443ea3715afade601ab31525ec66a2153222fa1db1ac859553977b43ad43f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
